### ISSUE TITLE
.NET MAUI iOS - System.DllNotFoundException: NcnnDotNetNative

### ISSUE THREAD

**Issue by usmanakram-dev** [takuya-takeuchi/UltraFaceDotNet#19]
I've developed a .NET MAUI App and used "UltraFaceDotNet" for face detection.

It works fine in Android but when I try to execute the same code for iOS it return with following exception

```
{System.DllNotFoundException: NcnnDotNetNative
   at NcnnDotNet.Net..ctor()
   at UltraFaceDotNet.UltraFace..ctor(UltraFaceParameter parameter)
   at UltraFaceDotNet.UltraFace.Create(UltraFaceParameter parameter)
   at CamView.Services.DetectService..ctor() in {MY-PROJECT-PATH}\DetectService.cs:line 76}
```

Line # 76 is where it's trying to Create UltraFace object from provided parameters as following

```
var param = new UltraFaceParameter
       {
           BinFilePath = binPath,
           ParamFilePath = paramPath,
           InputWidth = 320,
           InputLength = 240,
           NumThread = 1,
           ScoreThreshold = 0.7f
       };

       this._UltraFace = UltraFace.Create(param);
```
       
Following are the libraries and files I've used
       
![image](https://github.com/user-attachments/assets/3a75581f-16de-47b1-bdd7-8e4a60686a6a)

It also created link to following Libs

![image](https://github.com/user-attachments/assets/34e43627-2884-4551-92a8-b9cb29080002)

Can you please help to find out the issue? 

Many Thanks

**Comment by andersonvieiragomeslopes** [comment]
Hi @ITBrainSol 

I tried it on my iOS and it didn't work, but it also doesn't generate errors. Did you try adding this?

`<MtouchExtraArgs>-gcc_flags "-lc++ -framework Metal"</MtouchExtraArgs>
`

I'll try adding it here and see if it works. It works fine on my Android, but not on iOS.

**Comment by zerokewl88** [comment]
Facing the same issue, and adding to the Additional Arguments suggestion above, didn't change the result. 

<img width="404" height="98" alt="Image" src="https://github.com/user-attachments/assets/63e0bddb-14c1-402f-85ea-024fd8a0ff3f" />

<img width="2215" height="278" alt="Image" src="https://github.com/user-attachments/assets/17f823f0-9cce-4a95-a134-49dffb88e484" />

Also, adding that to the .csproj file under the ios section, also didn't resolve this. 

<PropertyGroup Condition="'$(TargetFramework)'=='net9.0-ios'">
  <MtouchExtraArgs>-gcc_flags "-lc++ -framework Metal"</MtouchExtraArgs>
</PropertyGroup>

**Comment by zerokewl88** [comment]
Trying to use and load UltraFaceDotNet (Xamarin) on Maui, and it works great on Android, but having trouble with the missing library for IOS. 

Is there are tips / advice that you could give to get this to work please?


```
{System.DllNotFoundException: NcnnDotNetNative
   at NcnnDotNet.Net..ctor()
   at UltraFaceDotNet.UltraFace..ctor(UltraFaceParameter parameter)
   at UltraFaceDotNet.UltraFace.Create(UltraFaceParameter parameter)
.....


```


I've tried adding 

<img width="305" height="55" alt="Image" src="https://github.com/user-attachments/assets/63cd2a38-1e00-4b70-827b-c53f92b9700f" />

<img width="500" height="64" alt="Image" src="https://github.com/user-attachments/assets/91b707ce-add4-48f1-809c-827e2dcc411b" />


This works for Android, but for IOS, having the above DLLNotFoundException being thrown.

**Comment by robitsrl** [comment]
Hello everybody,
any updates about the iOS problem ?
Thank's
